import 'package:intl/intl.dart';

export 'styles.dart';

const String kTitlePage = 'Flutter FieldPass';
const String kSigninText = 'Sign in with Microsoft';
const String kMicrosoftImage = 'assets/images/microsoft.png';
const String kImprint = 'Impressum  ';
const String kPrivacy = '  Datenschutz';
const String kMyAccount = 'Mein Konto';
const String kAssembler = 'Monteur';
const String kSuperior = 'Vorgesetzte';
const String kWeeklyReport = 'Wochenbericht';
const String kSendWeeklyReport = 'Wochenbericht zuschicken';
const String kMonthlyReport = 'Monatsbericht ';
const String kSendMonthlyReport = 'Monatsbericht erstellen';
const String kOverview = 'Übersicht';
const String kAnnualLeave = 'Jahresurlaub';
const String kRemainingVacationEPOS = 'Resturlaub EPOS';
const String kRequested = 'Beantragt';
const String kCarryOverFromPreviousYear = 'Übertrag Vorjahr';
const String kDateOfExpiry = 'gültig bis';
const String kApplyForLeave = 'Urlaub beantragen';
const String kCurrentBudget = 'Aktuelles Budget';
const String kSickDays = 'Krankheitstage';
const String kAll = 'Insgesamt';
const String kSubmitIlness = 'Krankheit einreichen';
const String kAzAccount = 'AZ Konto';
const String kHours = 'Stunden';
const String kMyBusinessCard = 'Meine Visitenkarte';
const String kBusinessCard = 'Visitenkarte ';
const String kAddress = 'Adresse';
const String kContact = 'Kontakt';
const String kHeadOfDepartment = 'Abteilungsleiter';
const String kOpen = 'Offen';
const String kTotalWorkingHours = 'Arbeitszeiten insgesamt für Heute';
const String kTimeTracking = 'Zeiterfassung';
const String kLogout = 'Ausloggen';
const double kMobileWidth = 500;
const String kQRUser = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
const String kQRSuperior = 'https://www.youtube.com/watch?v=9_gkpYORQLU';
const double kMaxWidth = 450;
final String dateToday = DateFormat('MM.dd.yyyy').format(DateTime.now());
const String kMonth = 'Monat';
const String kYear = 'Jahr';
const String kPeriod = 'Zeitraum';
const String kDaysTotal = 'Tage insgesamt';
const String kVacationDaysRequested = 'Beantragte Urlaubstage';
const String kCurrentHolidayBudget = 'Aktuelles Urlaubsbudget';
const String kComment = 'Bemerkung hinzufügen';
const String kVacation = 'Urlaub';
const String kStated = 'Wie angegeben';
const String kRepresentedBy = 'Vertretung durch';
const String kSend = 'Abschicken';
const String kWorkingTime = 'Arbeitszeit';
const String kBreak = 'Pause';
const String kCategory = 'Kategorie';
const String kProjectNumber = 'Projektnummer';
const String kEmployee = 'Mitarbeiter';
const String kPleaseSelectCategory = 'Wahlen Sie bitte Kategorie aus';
const String kAddPojectNumber = 'Projektnummer hinzufügen';
const String kAddOrEdit = 'hinzufügen oder bearbeiten';
const String kAbort = 'Abbrechen';
const String kSave = 'Speichern';
const String kWaitingPeriod = 'Wartezeit';
const String kStandBy = 'Bereitschaftszeit';
const String kProject = 'Projekt: 123456789';
const String kSitePreparation = 'Bereitschaftszeit';
