/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData first_aid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter_logo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_arrow = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_black = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoft = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_white = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_red = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_black = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_grey = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visitenkarte = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_black = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_white = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow_black = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow_white = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData begin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bet = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_card = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_dotted = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_black = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_white = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_arrow = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_down_arrow = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_grey = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_white = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
